Check for active processes before restore

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -172,6 +172,14 @@ if $instance_configured; then
     fi
 fi
 
+# Make sure the GitHub appliance has no active processes.
+if $instance_configured; then
+    if ! ghe-maintenance-mode-processes "$GHE_HOSTNAME"; then
+        echo "Error: $GHE_HOSTNAME has active processes. These must finish before starting a restore. Aborting." 1>&2
+        exit 1
+    fi
+fi
+
 # Make sure the appliance doesn't already have a restore underway
 if [ "$GHE_VERSION_MAJOR" -ge 2 ] && ghe-ssh "$GHE_HOSTNAME" -- "sudo grep -q restoring $GHE_REMOTE_DATA_USER_DIR/common/ghe-restore-status 2>/dev/null"; then
     echo "Error: $GHE_HOSTNAME already has a restore underway. Aborting." 1>&2
